# Generated by Django 3.0.8 on 2023-08-12 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasReffiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reffiling_size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gas')),
            ],
            options={
                'verbose_name': 'GasReffiling',
                'verbose_name_plural': '3.Gas Reffiling',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gas_reffiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.GasReffiling')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': '4.Stock',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': '1. Delivery Staff',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_number', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('id_proof', models.ImageField(upload_to='connection')),
                ('status', models.CharField(choices=[('1', 'Approved'), ('2', 'On Hold'), ('3', 'Rejected')], default='2', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': '2. New Connection',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=10, unique=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Confirmed'), ('2', 'On The Way'), ('3', 'Delivered')], max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.Connection')),
                ('reffiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.GasReffiling')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gas.Staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_change_status', 'Can Change Status'),),
            },
        ),
    ]
