# Generated by Django 3.0.8 on 2023-08-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Confirmed'), ('2', 'On The Way'), ('3', 'Delivered')], default='Confirmed', max_length=10, null=True),
        ),
    ]
